# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: algohmp@gmail.com
author_name: knonode
contract_name: hello_world
preset_name: production
project_name: signzero

